ALTER TABLE RESTRICTED_IDS DROP COLUMN modified_by;
ALTER TABLE RESTRICTED_IDS DROP COLUMN modified_time;
ALTER TABLE RESTRICTED_IDS DROP COLUMN modified_time_human;

CREATE UNIQUE INDEX IF NOT EXISTS RESTRICTED_IDS_ID_IN ON RESTRICTED_IDS(ID);
CREATE INDEX IF NOT EXISTS RESTRICTED_IDS_ID_VALUE_PLATFORM_IN ON RESTRICTED_IDS(ID_VALUE,PLATFORM);